### ISSUE TITLE
Question about listeners/setup (espeicially in Docker)

### ISSUE THREAD

**Issue by JohnOmernik** [VerizonDigital/vflow#10]
I am looking to run this in Apache Mesos (great setup by the way) based on the architecture page, it looks like I can run multiple instances of this to sync up together for HA etc, however, because they use multicast, I'd have to run my docker daemons in host mode for that to work?  (Please correct me if I am wrong). 

Thanks!

**Comment by mehrdadrad** [comment]
@JohnOmernik I haven't tried it with Apache Mesos.

**Comment by JohnOmernik** [comment]
So it's not really related to Mesos (the question).  I am more asking about running with multiple instances of vflow working together. I.e. if they are tied together using multicast as the approach... that won't be possible if you are running vflow in docker and using bridge mode.  Correct? This requires us to run the docker containers in host mode so the daemon can actually listen on a host multicast address... not a bridged one... is this correct?

If this is the case, could we consider providing a list of "other" vflow node IP/Ports to have nodes try to register with rather than using Multicast?

Thanks

**Comment by mehrdadrad** [comment]
I think bridge mode should work. it doesn't have any config in regard to multicast nodes but that's nice to add this feature. in case the multicast doesn't work you just lose data once you start the vFlow for first time (short time based on the device template interval configuration) and once a template added in device(s).
