### ISSUE TITLE
Netflow v5 is not starting

### ISSUE THREAD

**Issue by eksantrik** [VerizonDigital/vflow#106]
Hi folks,

I installed vflow 0.7 from rpm. When I start the service, I can see that Netflowv9, IPFIX and Sflow start fine but there is no trace for Netflow v5 on port 9996. I cannot see any attempt in vflow.log either.

I did not configure anything specific in the conf file since the feature is supposed to be enabled by default.

What am I missing?

**Comment by z3rohour** [comment]
I'd recommend to compile vFlow from the sources. It seems like rpm package hasn't been updated for a while as well as docker image from dockerhub

**Comment by eksantrik** [comment]
thanks. I compiled from source and swapped the file with the one installed as part of rpm. Everything seems to be working fine.
