### ISSUE TITLE
I get error

### ISSUE THREAD

**Issue by aaaasssdd** [VerizonDigital/vflow#11]
C:\Users\59401>go get github.com/VerizonDigital/vflow/vflow
# github.com/VerizonDigital/vflow/mirror
d:\users\go\src\github.com\VerizonDigital\vflow\mirror\mirror.go:65: undefined: syscall.IPPROTO_RAW
d:\users\go\src\github.com\VerizonDigital\vflow\mirror\mirror.go:88: cannot assign syscall.Handle to conn.fd (type int) in multiple assignment
d:\users\go\src\github.com\VerizonDigital\vflow\mirror\mirror.go:95: cannot use c.fd (type int) as type syscall.Handle in argument to syscall.Sendto
d:\users\go\src\github.com\VerizonDigital\vflow\mirror\mirror.go:100: cannot use c.fd (type int) as type syscall.Handle in argument to syscall.Close
# github.com/VerizonDigital/vflow/producer
d:\users\go\src\github.com\VerizonDigital\vflow\producer\kafka.go:78: undefined: sarama.CompressionLZ4

**Comment by mehrdadrad** [comment]
I haven't tried to compile for Windows, but you can compile it on a Linux OS without error.
It tested and works in production on the Linux Ubuntu 14.04 trusty. I'll update the document in this case.

**Comment by aaaasssdd** [comment]
I can use centos ?

**Comment by mehrdadrad** [comment]
@aaaasssdd it should be fine, please let us know the result here once you tried. Thanks!

**Comment by aaaasssdd** [comment]
Wait till I finish testing.

**Comment by mehrdadrad** [comment]
@aaaasssdd any update?

**Comment by tanaboon** [comment]
I use centos 7
run docker & brows http://127.0.0.1:8081
show 404 page not found
Can you help me that how to use it.

**Comment by mehrdadrad** [comment]
You need to call them as below and these two APIs return the internal metrics. if you have plan to try it through Docker, you need to configure at least a device or a host which they support IPFIX / sFlow.

Flow API : http://localhost:8081/flow
```
{
   "IPFIX" : {
      "MessageQueue" : 0,
      "DecodedCount" : 733,
      "MQErrorCount" : 0,
      "UDPCount" : 733,
      "UDPMirrorQueue" : 0,
      "UDPQueue" : 0,
      "Workers" : 100
   },
   "SFlow" : {
      "MessageQueue" : 0,
      "UDPCount" : 268,
      "MQErrorCount" : 0,
      "DecodedCount" : 253,
      "UDPQueue" : 0,
      "Workers" : 100
   },
   "StartTime" : 1490134512
}
```
System API : http://localhost:8081/sys
```
{
   "GCSys" : 450560,
   "MemTotalAlloc" : 11435376,
   "MCacheInuse" : 4800,
   "GCNext" : 5053510,
   "MemHeapReleased" : 0,
   "NumGoroutine" : 237,
   "GoVersion" : "go1.7.4",
   "NumLogicalCPU" : 4,
   "GCLast" : "2017-03-21 22:17:50.923246779 +0000 UTC",
   "MemHeapAlloc" : 4151416,
   "MemAlloc" : 4151416,
   "StartTime" : 1490134512,
   "MemHeapSys" : 5734400
}
```

**Comment by mehrdadrad** [comment]
@aaaasssdd 
@jrossi fixed the mirror compiling issue at Windows which now you can compile it at Windows OS without having mirror feature, could you please try it w/ latest code and let us know? Thanks!
