### ISSUE TITLE
Error on cisco ipfix template save

### ISSUE THREAD

**Issue by rtsam** [VerizonDigital/vflow#12]
[vflow] 2017/05/28 08:39:25 couldn't not dump template json: unsupported type: map[uint32]ipfix.Data

**Comment by mehrdadrad** [comment]
Does it work before dumping? Please let me know the below info:
1- device model and IOS
2- operating system
3- go version

**Comment by rtsam** [comment]
It does... works wonderfully. There are template errors when vflow is started after a flow is already running, (unknown ipfix template id# 257) however adding "template data timeout 300" to the exporter causes a template resend every 5 minutes. And works fine after that.

Also, here is what we are exporting (i am guessing it does not know how to save one of the fields?)...

flow record NetFlowRecord
 match ipv4 protocol
 match ipv4 source address
 match ipv4 destination address
 match transport source-port
 match transport destination-port
 collect counter bytes
 collect counter packets
 collect routing next-hop address ipv4
 collect interface output
 collect interface input
 collect flow direction

1 Cisco CISCO2911/K9 IOS: Version 15.0(1r)M16
2. Ubuntu 16.04 4.4.0-62-generic #83-Ubuntu
3. go version go1.6.2 linux/amd64

**Comment by mehrdadrad** [comment]
@rtsam did you compile the latest code? cuz we had a dump issue a few months ago but it fixed and i just tried again at our network (Juniper) and works. we have all of your fields. can you compile w/ go 1.8.x as well and try again? Thanks!

**Comment by rtsam** [comment]
I did... just set everything up last week. So the code would be recent. However I just upgraded go to 1.8.1. And it is dumping the templates now. So the conclusion is; the version of go that comes with Ubuntu was the problem. Thanks!

**Comment by mehrdadrad** [comment]
@rtsam very cool :) no idea why 1.6.2 caused this issue but I'm happy the Go upgrade fix this issue.
