### ISSUE TITLE
Applying UDPCount and DecodedCount values to performance

### ISSUE THREAD

**Issue by eksantrik** [VerizonDigital/vflow#120]
We are doing some performance tests in the lab. After generating a bunch of Netflow v5 traffic in the lab, we stopped the packet generator and after 5 minutes we stopped vflow service on the machine. Following is what we see in the stats page:

{"StartTime":1571769677,"IPFIX":{"UDPQueue":0,"UDPMirrorQueue":0,"MessageQueue":0,"UDPCount":0,"DecodedCount":0,"MQErrorCount":0,"Workers":10},"SFlow":{"UDPQueue":0,"MessageQueue":0,"UDPCount":0,"DecodedCount":0,"MQErrorCount":0,"Workers":10},"NetflowV5":{"UDPQueue":0,"MessageQueue":0,"UDPCount":347410,"DecodedCount":187848,"MQErrorCount":0,"Workers":500},"NetflowV9":{"UDPQueue":0,"MessageQueue":0,"UDPCount":0,"DecodedCount":0,"MQErrorCount":0,"Workers":10}}

My question is simple. What does the difference between UDPCount and DecodedCount mean? Since there is a difference and vflow is not trying to close it, does that mean that we lost packets in the process?

Thanks,

**Comment by eksantrik** [comment]
I am not sure if it is relevant but our simulation is sending 30 flows in a single Netflowv5 packet.

**Comment by mehrdadrad** [comment]
Can you try 1k per seconds w/ less than 5 samples per packet? then check again the counters
p.s. you need to reset the counters by restarting the vflow.
