### ISSUE TITLE
can't stop service when pid has 6 digits and after restart has 5 digits

### ISSUE THREAD

**Issue by guyyur** [VerizonDigital/vflow#124]
In vflow/options.go the PIDFile is opened with os.O_WRONLY|os.O_CREATE without truncating the file.

I had a scenario where vflow received pid 229006 crashed then restarted and received pid 92419.
The pidfile had 924196 (5 digits from new pid and 6th digit from old pid) and the process could not be stopped by "service vflow stop".

Because vflow crashed it did not clear the pidfile which happens in "service vflow stop"

**Comment by mehrdadrad** [comment]
@guyyur Thanks! it just fixed
