### ISSUE TITLE
Where to begin?

### ISSUE THREAD

**Issue by bdollma** [VerizonDigital/vflow#127]
Hi, 
I found this project today and I am trying to find some documentation, but except for some short read me in the Github, I can't find anything. Is there something somewhere?
Anyhow,  I am trying to do something very simple. I have IPFix traffic incoming to one of the interfaces at port 4739.
I simply want to see the decoded JSON (easiest use case ever) of each packet. As a start, scale wouldn't matter.
What is the best way to do this? From what I understand, you can mirror the decoded data to a Netflow collector, but isn't **vflow** a Netflow collector? Do I need another Netflow collector?
Thanks

**Comment by mehrdadrad** [comment]
The easiest way to try and see the decoded samples on the console without mq is the below command:
```
vflow -mqueue nsq -verbose true
```
