### ISSUE TITLE
Support for expanded sflow

### ISSUE THREAD

**Issue by ttrading** [VerizonDigital/vflow#141]
Does vflow support expanded sflow? We recently had an issue sending sflow data to vflow from a couple of Nexus 3K switches and we believe they are sending expanded flow and counter data instead of compact.

Thanks,

**Comment by mehrdadrad** [comment]
It doesn't support expanded flow sample / type 3. It supports type 1 and 2.

**Comment by ttrading** [comment]
Is it in the roadmap? 

I saw a couple of other tickets with similar concerns because they were using Cisco Nexus switches. It may worth adding support for it at some point.

Thanks,

**Comment by mehrdadrad** [comment]
we don't have any plan for this.
