### ISSUE TITLE
API for vFlow Monitoring not working

### ISSUE THREAD

**Issue by Slepwin** [VerizonDigital/vflow#142]
Hi, I've error below when i'm trying to hit API http://localhost:8081/flow or http://localhost:8081/sys
`404 page not found`

Reproducible on docker and RPM/DEB packages.

**Comment by mehrdadrad** [comment]
The default format is prometheus. please try http://localhost:8081/metrics
You can change the format by stats-format  https://github.com/VerizonDigital/vflow/blob/master/docs/config.md
I just updated the documentations.

**Comment by Slepwin** [comment]
> The default format is prometheus. please try http://localhost:8081/metrics
> You can change the format by stats-format https://github.com/VerizonDigital/vflow/blob/master/docs/config.md
> I just updated the documentations.

Oh, my fault, thanks for help!
