### ISSUE TITLE
 unknown ipfix template

### ISSUE THREAD

**Issue by herc6** [VerizonDigital/vflow#20]
Hello,

I try to run vflow for collecting IPFIX data. When vflow receives the ipfix data I get the follow error
"unknown ipfix template id# 15599" and nothing is put onto kafka

regards,

**Comment by mehrdadrad** [comment]
- what's device or software which you tried to send IPFIX? 
- please try w/ latest version

**Comment by herc6** [comment]
I'm use version 0.4.1
The ipfix data is send from the procera server.
Using ipfixcat (https://github.com/calmh/ipfixcat)  it works fine

**Comment by mehrdadrad** [comment]
@herc6 Per [ipfixcat github](https://github.com/calmh/ipfixcat), it supports RFC 5101 so looks Procera sends IPFIX based on this RFC (old one) then you can see the parsed data by this tool. RFC 5101 obsoleted by RFC 7011 and the vFlow supports RFC 7011.
I'm not familiar w/ Procera but you can ask them to how you can update your IPFIX agent.
