### ISSUE TITLE
ipfix/netflow on on different ports

### ISSUE THREAD

**Issue by jrossi** [VerizonDigital/vflow#21]
Before I go and code things up.  ipfix and netflow run on different ports and this is not required.  A switch/if could be used on the first 2 bytes of the packet.  

Code to do this be accepted?

**Comment by mehrdadrad** [comment]
in this case we can listen a port for all protocols. kind of the below multiplexer:
https://github.com/soheilhy/cmux
I think the main issue is overhead once we have heavy load (more than 10Tbps). as I remember other flow collectors listen to diff ports. what's benefit of this feature?

**Comment by jrossi** [comment]
Not even that :) far simpler.  

https://github.com/VerizonDigital/vflow/blob/master/vflow/ipfix.go#L147

Something like: 
```go

       const (
              IPFixVersion uint16 = 0x000a
              VersionNetflowV9 uint16 =  0x0009
       ) 

	for !i.stop {
		b := ipfixBuffer.Get().([]byte)
		conn.SetReadDeadline(time.Now().Add(1e9))
		n, raddr, err := conn.ReadFromUDP(b)
		if err != nil {
			continue
		}
                switch binary.BigEndian.Uint16(b[:2]) {
                case IPFixVersion:
                        atomic.AddUint64(&ipfix.stats.UDPCount, 1)
                        ipfixUDPCh <- IPFIXUDPMsg{raddr, b[:n]}
                case VersionNetflowV9:
                        atomic.AddUint64(&netflow.stats.UDPCount, 1)
		        netflowV9UDPCh <- NetflowV9UDPMsg{raddr, b[:n]}
                default:
                        //Logging for unknown protocols here

	}

```

**Comment by mehrdadrad** [comment]
again, what's benefit of having a port instead of individual?
once we have two ports:
- two listeners from two goroutine, get the UDP packets, better performance to read UDP buffer
- should be faster as we don't check two bytes + make decision to send to appropriate channel
- I think when we have two listeners, we have two buffers at OS layer (less UDP drop)

**Comment by jrossi** [comment]
Sorry - wow - left this open forever.  For my use case I have many many different devices all pushing netflow and ipfix to the same port.  Have been doing this for ages.  Simpler for me when working with other teams.

**Comment by mehrdadrad** [comment]
np, we can have this as a utility: one specific UDP listener then it routes them to two diff ports based on the first two bytes. IPFIX source IP address should be same so it needs spoofing feature.
but if you have many diff devices + traffic so perf must be concerned so the diff ports should be better.
