### ISSUE TITLE
Visualizing flow information...

### ISSUE THREAD

**Issue by richb-hanover** [VerizonDigital/vflow#22]
Not a real issue, more a question... (I saw vflow mentioned on the NANOG list the other day.)

vflow sounds really impressive for big flow traffic. I am looking at a slightly different application space, and wonder if vflow might work.

I'm writing a series of blog posts about netflow collectors that are useful for home networks. (Even though you're a little guy, you still need good tools...) You can read them at http://richb-hanover.com/netflow-collectors-for-home-networks/)

If I'm reading the documentation correctly, vflow collects the flow data and puts it into a database. Do you have any recommendations about visualizing the data? I'd love to be able to recommend some kind of graphical front end for my readers. Many thanks!

**Comment by mehrdadrad** [comment]
@richb-hanover the vFlow produces data to the message bus (Kafka/NSQ/NATS) then you need to create your own consumer to insert to anywhere. depends on the load you need different strategies. one of the scenarios is ingesting to Elasticsearch then you can visualize them by Kibana. when you have mid-high load you need to have aggregation and warehousing. other solution could be TSDB/HBase w/ Grafana, Clickhouse, MemSQL w/ a BI. there are other valuable apps could be developed top of vFlow, like detect DDoS attack, anomaly detection w/ AI or network intruder detection.

**Comment by richb-hanover** [comment]
Thanks for this feedback. My focus is relatively low-traffic: home routers. 

I was wondering if you (or anyone else) have any examples of a graphical consumer that could show top talkers, top ports/protocols, etc. Thanks again.
