### ISSUE TITLE
cannot compile clickhouse/main.go

### ISSUE THREAD

**Issue by AlexeyStolyarov** [VerizonDigital/vflow#24]
when I trying 
`go build main.go`                                                                                                                        

Ive got 

```
[master] 
# github.com/kshvakov/clickhouse/lib/data
../../../src/github.com/kshvakov/clickhouse/lib/data/block.go:74: invalid variable name column in type switch
../../../src/github.com/kshvakov/clickhouse/lib/data/block.go:89: undefined: column.ReadArray
../../../src/github.com/kshvakov/clickhouse/lib/data/block.go:96: undefined: column.Read
../../../src/github.com/kshvakov/clickhouse/lib/data/block.go:115: invalid variable name column in type switch
../../../src/github.com/kshvakov/clickhouse/lib/data/block.go:117: undefined: column.WriteArray
../../../src/github.com/kshvakov/clickhouse/lib/data/block.go:126: undefined: column.Write


```
solution I have found:
`cd <src/kshvakov/clickhouse> && make  git checkout  3d7bd11  `
(this rollbacks codebase to date when last commit was made in your repo)

**Comment by mehrdadrad** [comment]
I just tried w/ latest version of clickhouse package: c4eeaf6 and main.go built w/o error. @kshvakov had few commits 6-8 hours ago, pls try again w/ latest and see how it works for u.

**Comment by AlexeyStolyarov** [comment]
Nope. The same error.
last commit in kshvakov repo is that I got
```
 commit c4eeaf60bc780d3de38be9548103d2303ce110cf
Author: kshvakov <shvakov@gmail.com>
Date:   Wed Aug 30 13:18:55 2017 +0300

```

suppose the reason is my environment
Ive got:
```
Ubuntu 17.04 /x64. kernel 4.10.0-28-generic
go version go1.7.4 linux/amd64
```

**Comment by kshvakov** [comment]
@AlexeyStolyarov Go 1.7 isn't supported by ClickHouse driver, the minimum version of Go is 1.8
