### ISSUE TITLE
mq config examples

### ISSUE THREAD

**Issue by fgbs** [VerizonDigital/vflow#28]
Hello all,

Only kafka publisher examples available, but nothing for NATS and NSQ.

**Comment by mehrdadrad** [comment]
@fgbs NSQ quick start: https://github.com/VerizonDigital/vflow/blob/master/docs/quick_start_nsq.md

**Comment by fgbs** [comment]
@mehrdadrad these example only works if you hace NSQ in the same host because is [hardcoded](https://github.com/fgbs/vflow/blob/master/producer/nsq.go#L53), the same apply to [NATS](https://github.com/fgbs/vflow/blob/master/producer/nats.go#L48)

**Comment by mehrdadrad** [comment]
@fgbs can you try below for NSQ:
edit /etc/vflow/mq.conf and add below:
-server: hostaddress:port

**Comment by mehrdadrad** [comment]
I did minor changes at code and update [config](https://github.com/VerizonDigital/vflow/blob/master/docs/config.md) doc.
NSQ same as before:  
server: host:port
NATS:
url: url
