### ISSUE TITLE
Netflow: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by franks231** [VerizonDigital/vflow#29]
Hello All,
 
i get "fatal error: runtime: out of memory" after some minutes vflow is running 
and this is my vflow.conf:

netflow9-workers: 50
log-file: /var/log/vflow.log
ipfix-tpl-cache-file: /usr/local/vflow/vflow.templates
netflow9-topic: anomaly
ipfix-enabled: false
sflow-enabled: false
dynamic-workers: false

**Comment by mehrdadrad** [comment]
pls give me more info:
- did you compile? Go version? what OS?
- device vendor(s)?
- messaging bus?
- hardware spec? dedicated or shared between other apps
- attach the fatal error details

**Comment by franks231** [comment]
Hi mehrdad,

1- yes i compile that, go version go1.8.3 linux/amd64 , ubuntu 16.04
2- Cisco netflow9
3- Kafka
4- VM, dedicate, 20 Core vcore + 16GB memory
5- https://pastebin.com/12iEidT8

**Comment by mehrdadrad** [comment]
@franks231 I tried in my dev box and I couldn't duplicate this issue yet.
- can you check the vflow log file and send me if there is any logging
- can you try without the below configs:
ipfix-enabled: false
sflow-enabled: false
dynamic-workers: false

**Comment by franks231** [comment]
@mehrdadrad 
i try without this 3 lines but vflow crash again

and this is a vflow sample logs


- unexpected EOF
- can not read the data
- can not read the data
- can not read the data
[vflow] 2017/10/03 18:13:30 Multiple errors:
- can not read the data
- unexpected EOF
- can not read the data
- can not read the data
- can not read the data
- can not read the data
- can not read the data
10.234.233.16 unknown netflow template id# 1536
- unexpected EOF
- can not read the data
- can not read the data
- can not read the data
[vflow] 2017/10/03 18:14:11 Multiple errors:
- can not read the data
- unexpected EOF
- can not read the data
- can not read the data
- can not read the data
[vflow] 2017/10/03 18:15:47 Multiple errors:
- can not read the data
- unexpected EOF
- can not read the data
- can not read the data
- can not read the data
- unexpected EOF
- can not read the data
- can not read the data
- can not read the data
- can not read the data
- can not read the data

**Comment by mehrdadrad** [comment]
@franks231 What's Netflow version configured at router? can I have the configuration?

**Comment by franks231** [comment]
@mehrdadrad  netflow is version 9 
I don't have access right now but I send the configuration asap

**Comment by jan-zajic** [comment]
Hello All, we have same error, config file:
ipfix-enabled: false
sflow-enabled: false
netflow9-enabled: true
ipfix-workers: 1
sflow-workers: 1
netflow9-workers: 5
netflow9-port: 10000
dynamic-workers: false
send to kafka topic.
Crash about every 5 minutes. Collect correct data in between. 

[vflow-netflow-log.txt](https://github.com/VerizonDigital/vflow/files/1430981/vflow-netflow-log.txt)
[vflow-netflow-crash.txt](https://github.com/VerizonDigital/vflow/files/1430976/vflow-netflow-crash.txt)

**Comment by mehrdadrad** [comment]
@jan-zajic what's device vendor name? can you send me your device netflow 9 config?

**Comment by mehrdadrad** [comment]
@jan-zajic I think it should be fixed based on the recent changes, pls try again and let me know if you still see this issue.
