### ISSUE TITLE
NetFlow V9 support

### ISSUE THREAD

**Issue by fartbagxp** [VerizonDigital/vflow#3]
Hi, I was wondering if there is any plan on doing ~sFlow~ NetFlow v9 support.

Thanks!

**Comment by mehrdadrad** [comment]
@fartbagxp if you mean NetFlow v9, I think we need to get at least few requests , then we can prioritize it. I personally would like to add this protocol.

**Comment by fartbagxp** [comment]
Yeah, sorry about that. I was looking for NetFlow V9 support.
Other than that, I'm planning on trying this out.

Is stress what you use to test it out locally?

**Comment by mehrdadrad** [comment]
@fartbagxp a few sample flow data hard coded at the stress and it can be able to send them to any ipfix/sflow collector through IP network.

**Comment by mehrdadrad** [comment]
@fartbagxp I just initialized a new package for NetFlow v9 but as it's not priority no idea when it will be done.

**Comment by mehrdadrad** [comment]
@fartbagxp the netflow version 9 already added to the vFlow. I tried it w/ nprobe and works but I think still we need to test and make sure everything works properly.
