### ISSUE TITLE
 Can vflow support distributed deployment and plugins ？

### ISSUE THREAD

**Issue by JasonLZJ** [VerizonDigital/vflow#33]
How many QPS supports a single machine?

Do you support plugins to support other protocols? such as NetStream, CFlowd ?

thanks

**Comment by mehrdadrad** [comment]
@JasonLZJ I tried w/ Dell R620 and it could handle more than 80K IPFIX UDP packet per second (assuming 5 samples per packet) + producing data to Kafka.
You can write any sampling protocol w/ Golang and add to vFlow, that's very straightforward as already I did three protocols. please check the [arch](https://github.com/VerizonDigital/vflow/blob/master/docs/design.md)
