### ISSUE TITLE
latest version from git "operation not supported" when running

### ISSUE THREAD

**Issue by paolss** [VerizonDigital/vflow#36]
Hi 
Just trying to install and run
configs:
cat /etc/vflow/vflow.conf
ipfix-workers: 600
sflow-workers: 300
sflow-port: 9999
stats-http-port: 10080
log-file: /var/log/vflow.log

cat /etc/vflow/mq.conf
brokers:
    - 127.0.0.1:9092
retry-max: 1
retry-backoff: 30

netstat -na | grep 9092
netstat -na | grep 9092
tcp6       0      0 :::9092                 :::*                    LISTEN

logs for vflow with -verbose show no errors - last in log:
[vflow] 2017/11/06 19:51:20 netflow v9 is running (UDP: listening on [::]:4729 workers#: 200)
[vflow] 2017/11/06 19:51:20 ipfix is running (UDP: listening on [::]:4739 workers#: 600)

**Comment by paolss** [comment]
complete log:
[vflow] 2017/11/06 19:54:31 Welcome to vFlow v.unknown Apache License 2.0
[vflow] 2017/11/06 19:54:31 Copyright (C) 2017 Verizon. github.com/VerizonDigital/vflow
[vflow] 2017/11/06 19:54:31 starting stats web server ...
[vflow] 2017/11/06 19:54:31 ipfix is running (UDP: listening on [::]:4739 workers#: 600)
[vflow] 2017/11/06 19:54:31 netflow v9 is running (UDP: listening on [::]:4729 workers#: 200)
[vflow] 2017/11/06 19:54:31 sFlow is running (UDP: listening on [::]:9999 workers#: 300)
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.22.158:44994, size: 1264 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.22.158:44994, size: 1260 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.32.21:39614, size: 1316 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.22.158:44994, size: 1320 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.22.158:44994, size: 1368 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.32.71:52545, size: 1284 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.32.21:39614, size: 1316 bytes
[vflow] 2017/11/06 19:54:31 rcvd sflow data from: 192.168.32.71:52545, size: 1360 bytes

and operation not supported
but pid created:
cat /var/run/vflow.pid
2329

with no running process:
ps aux | grep vflow
root      2430  0.0  0.0   9072   916 pts/0    S+   19:55   0:00 grep --colour=auto vflow

**Comment by mehrdadrad** [comment]
the error: "operation not supported" appears on your console not log right? looks this error related to storage. did you set file access control lists?

**Comment by paolss** [comment]
yes operation not supported appears on console when starting

**Comment by paolss** [comment]
file access control list ?
Is this in configuration ?
I just configured vflof.conf with sflow/netflow + mq for kafka

**Comment by mehrdadrad** [comment]
this error doesn't come from vFlow, if you google "operation not supported" you can see the results are related to storage. I think there is a limitation on your host which causes this issue.

**Comment by paolss** [comment]
No this is not file permission problem 
2017/11/06 22:15:04 operation not supported

And im trying to start vflow by root - so cant have file permission problems - and no selinux enabled

After deleting config files:
[vflow] 2017/11/06 22:17:19 open /etc/vflow/vflow.conf: no such file or directory
[vflow] 2017/11/06 22:17:19 Welcome to vFlow v.unknown Apache License 2.0
[vflow] 2017/11/06 22:17:19 Copyright (C) 2017 Verizon. github.com/VerizonDigital/vflow
[vflow] 2017/11/06 22:17:19 starting stats web server ...
[vflow] 2017/11/06 22:17:19 listen udp :6343: bind: address already in use

But yes i have other daemon listening on 6343
bu change:
./vflow -sflow-port 9999
[vflow] 2017/11/06 22:18:31 open /etc/vflow/vflow.conf: no such file or directory
[vflow] 2017/11/06 22:18:31 Welcome to vFlow v.unknown Apache License 2.0
[vflow] 2017/11/06 22:18:31 Copyright (C) 2017 Verizon. github.com/VerizonDigital/vflow
[vflow] 2017/11/06 22:18:31 starting stats web server ...
[vflow] 2017/11/06 22:18:31 ipfix is running (UDP: listening on [::]:4739 workers#: 200)
[vflow] 2017/11/06 22:18:31 netflow v9 is running (UDP: listening on [::]:4729 workers#: 200)
[vflow] 2017/11/06 22:18:31 sFlow is running (UDP: listening on [::]:9999 workers#: 200)
[vflow] 2017/11/06 22:18:31 open /etc/vflow/mq.conf: no such file or directory
[vflow] 2017/11/06 22:18:31 open /etc/vflow/mq.conf: no such file or directory
[vflow] 2017/11/06 22:18:31 open /etc/vflow/mq.conf: no such file or directory
2017/11/06 22:18:31 operation not supported

What vflow is doing after binding sockets ?

**Comment by paolss** [comment]
it is starting to receive some sflow data also
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.138:48681, size: 1328 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.72:58213, size: 1372 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.21:39614, size: 1372 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.21:39614, size: 1224 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.28:56378, size: 1388 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.72:58213, size: 1304 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.28:56378, size: 1216 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.116:38360, size: 1340 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.116:38360, size: 1364 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.21:39614, size: 1248 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.28:56378, size: 1260 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.114:57389, size: 1344 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.114:57389, size: 1328 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.61:38528, size: 1384 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.114:57389, size: 1340 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.72:58213, size: 1268 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.138:48681, size: 1304 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.61:38528, size: 1372 bytes
[vflow] 2017/11/06 22:20:34 {"Header":{"Version":5,"IPVersion":1,"AgentSubID":0,"SequenceNo":310786390,"SysUpTime":327608940,"SamplesNo":7,"IPAddress":"192.168.32.72"},"ExtSWData":null,"Sample":{"SequenceNo":385398112,"SourceID":0,"SamplingRate":8192,"SamplePool":380370944,"Drops":0,"Input":1061,"Output":1007,"RecordsNo":1},"Packet":{"L2":{"SrcMAC":"00:0b:cd:fe:59:2e","DstMAC":"00:25:90:ca:aa:a4","Vlan":1115,"EtherType":2048},"L3":{"Version":4,"TOS":0,"TotalLen":327,"ID":52859,"Flags":0,"FragOff":0,"TTL":57,"Protocol":17,"Checksum":1022,"Src":"172.16.0.1","Dst":"192.168.33.22"},"L4":{"SrcPort":48996,"DstPort":80}}}
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.128:41304, size: 1284 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.32.28:56378, size: 1388 bytes
[vflow] 2017/11/06 22:20:34 rcvd sflow data from: 192.168.22.114:57389, size: 1252 bytes
2017/11/06 22:20:34 operation not supported

And just after operation not supported

**Comment by mehrdadrad** [comment]
did you configure mq.conf? what messaging bus you're using?

**Comment by paolss** [comment]
as I posted on first message.
mq.conf / vflow.conf 
broker kafka

But now for debug i deleted config files to check what happens

**Comment by nuclearcat** [comment]
Happened with me as well, culprit is in
2018/05/31 10:27:22 memcache_rpc.go:144: operation not supported
Line: disc, err := vFlowDiscovery()
Everything works if i put in config:
ipfix-rpc-enabled: false

btw it might be handy to add in options.go, GetOptions() this:
`	if opts.Verbose == true {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
	}
`
