### ISSUE TITLE
dependency management

### ISSUE THREAD

**Issue by mmlb** [VerizonDigital/vflow#38]
Running `go get ./...` strikes me as not the greatest thing to be doing, any thoughts on using a package manager to handle the deps?

I ran `dep init .` and found many of the dependencies to have sane versions released.

**Comment by mehrdadrad** [comment]
@mmlb pls post more details about this.

**Comment by mehrdadrad** [comment]
@mmlb it's not necessary, thanks!

**Comment by mmlb** [comment]
@mehrdadrad can you expand on why you think it is not necessary? If build vflow today I have no guarantees that when I go to build it next month that it will build again. Both sarama-cluster and gopkg.in/yaml are at major version 2 which is evidence of this happening once before and possible in the future.
