### ISSUE TITLE
question about configure

### ISSUE THREAD

**Issue by dpicollege** [VerizonDigital/vflow#4]
Hello,
i install and run docker. so i have some question
1- ok is there any interface or log file for see the output?
2- i just installed on ubuntu 16 does i need cisco or juniper router to send data to ubuntu?
3-what configure should i change to send traffic to vflow?
and lot's of more question thanks :D for great project!

**Comment by mehrdadrad** [comment]
Hi @dpicollege, 
You need to have IPFIX/sFlow agent like Juniper or any other software which they export traffic sampling through IPFIX/sFlow. I'll try to put example configuration at docs soon and update here too.
You can mount local docker host to the container like below to see the log:
```
mkdir -p /tmp/vflow/etc /tmp/vflow/log
echo "log-file: /var/log/vflow/vflow.log" > /tmp/vflow/etc/vflow.conf
docker run -d -p 4739:4739 -p 6343:6343 -p 8081:8081 -e VFLOW_KAFKA_BROKERS="172.17.0.1:9092" -v /tmp/vflow/etc:/usr/local/vflow/etc:ro -v /tmp/vflow/log:/var/log/vflow:rw -i mehrdadrad/vflow
tail -f /tmp/vflow/log/vflow.log
```

**Comment by lyma** [comment]
Hi @mehrdadrad !

Thank you for sharing this project!
Is there any interface (web, maybe) for output like in nfsen project?
Can you explain for me (a docker newbe) the docker parameters?

Regards.

Lyma

**Comment by mehrdadrad** [comment]
@lyma there isn't any built in UI but you can get / see the data through the below:
1- MemSQL (through SQL statement)
2- Kafka Consumer shell script (kafka-console-consumer.sh)
3- Through other scripting language like Python

vFlow has built in monitoring so you can see them through the API or InfluxDB/Grafana

In regard to docker,  you can try as below or above reply.
```
docker run -d -p 2181:2181 -p 9092:9092 spotify/kafka
docker run -d -p 4739:4739 -p 6343:6343 -p 8081:8081 -e VFLOW_KAFKA_BROKERS="172.17.0.1:9092" mehrdadrad/vflow
```

Please see the Build section, you can compile the vFlow quickly.

*The Netflow v9 feature still is not exist in docker image as it still works as beta version.
