### ISSUE TITLE
vflow with JunOS and netflow

### ISSUE THREAD

**Issue by gedOHub** [VerizonDigital/vflow#49]
Hello,

We are facing problem parsing netflow flow from Juniper MX960 running JunOS 13.3R9.13
Error:

> [vflow] 2018/01/31 15:41:52 181.41.211.9 unknown netflow template id# 257

vFlow runs on CentOS 7.4 3.10.0-693.17.1.el7.x86_64.
vFlow 0.4.1 was installed from package by https://github.com/VerizonDigital/vflow/blob/master/docs/quick_start_kafka.md

vFlow configuration left default:
`
ipfix-workers: 100
sflow-workers: 100
netflow9-workers: 50
log-file: /var/log/vflow.log
ipfix-tpl-cache-file: /usr/local/vflow/vflow.templates
`

We can't use any other flow because of other systems
Can you point me to right direction? 

We have dump if needed

**Comment by mehrdadrad** [comment]
@gedOHub 
I think it should be fixed at v0.5.0 can you compile the latest version? I'll try to upload the RPM and Debian package soon.

**Comment by gedOHub** [comment]
@mehrdadrad Thank you for response. I update you after I try it

**Comment by gedOHub** [comment]
@mehrdadrad Version 0.5.0 was able to parse netflow flow. Thank you for quick responce

**Comment by mehrdadrad** [comment]
Great! thanks for update!
