### ISSUE TITLE
Align the dockerfile with best practices

### ISSUE THREAD

**Issue by JPercivall** [VerizonDigital/vflow#51]
There are a number of improvements that could be done to the Dockerfile to better align it with best practices.

- Don't use supervisord and instead allow the user to utilize the docker restart policy
- Container should not stay alive when the vflow process ends
- Logs should be output as part of the docker logs
- Use a multistage build to reduce the size of the final image
- Use the official Golang and Alpine base images instead of Ubuntu

**Comment by JPercivall** [comment]
Will follow-up with a PR

**Comment by JPercivall** [comment]
PR here: https://github.com/VerizonDigital/vflow/pull/52

**Comment by mehrdadrad** [comment]
Thanks @JPercivall , It just merged
