### ISSUE TITLE
vflow don't work with sFlow from Cisco Nexus 3000

### ISSUE THREAD

**Issue by AlexAkulov** [VerizonDigital/vflow#53]
Hello!

I'm trying to collect sFlow from Cisco Nexus 3000 and it's doesn't work.
vflow received packages, it can be seen in verbose log, but queue is empty.
```
>$ ./vflow -verbose
...
[vflow] 2018/02/22 11:30:35 rcvd sflow data from: 10.0.51.150:62255, size: 1312 bytes
[vflow] 2018/02/22 11:30:35 rcvd sflow data from: 10.0.51.150:62255, size: 572 bytes
[vflow] 2018/02/22 11:30:35 rcvd sflow data from: 10.0.51.150:62255, size: 1368 bytes
```
I added debug log and found that processing packages stop here
https://github.com/VerizonDigital/vflow/blob/master/sflow/decoder.go#L137-L139
In my case `datagram.Version = 1` but my Cisco Nexus 3000 exactly sends sFlow v5.

I tried to use this https://github.com/Cistern/sflow go-library and it's doesn't work on my sFlow traffic too.

But this tool https://github.com/sflow/sflowtool works perfectly. Because I guess that bug in vflow.

I save my sflow traffic to [pcap](https://github.com/AlexAkulov/vflow/raw/master/sflow/sflow.pcap) over tcpdump, may be it will be useful.

**Comment by mehrdadrad** [comment]
@AlexAkulov no idea why version assigns w/ one as pcap shows it sends five but the main issue that I'm seeing at pcap is sample flow data type is 3 (ipv4 data) and vFlow supports "raw packet header"
