### ISSUE TITLE
Choosing right back end

### ISSUE THREAD

**Issue by gedOHub** [VerizonDigital/vflow#54]
Hello,

I and my company are testing `vFlow` for few weeks. For now we have about `45K` inserts per second and we using MySQL back end and we struggling for performance.

- Have you done any back end storage performance comparison? 
- Can you share with best practices choosing back end storage? 
- What back end storage you are using?

**Comment by mehrdadrad** [comment]
@gedOHub 
please check the clickhouse and others at https://github.com/VerizonDigital/vflow/tree/master/consumers 
I suggest you to have aggregation level then store somewhere for high and low resolution. I had good experience w/ clickhouse! but you can try OpenTSDB/HBase/HDFS
