### ISSUE TITLE
CRC error while pushing data to kafka

### ISSUE THREAD

**Issue by gedOHub** [VerizonDigital/vflow#56]
Hello

I have used vFlow in production and notices that logs like 

> kafka: Failed to produce message to topic chipmunk.vflow: kafka server: Message contents does not match its CRC.

have appeared in vFlow logs. How I can determinate that issue is in kafka or in vFlow side?

I'm running:

> vFlow version: 0.5.0
> go version go1.10.1 linux/amd64
> kafka_2.11-1.1.0
> ZooKeeper 3.4.11

**Comment by mehrdadrad** [comment]
@gedOHub I couldn't duplicate this issue.

**Comment by gedOHub** [comment]
Problem didn't come back again. Closing issue for now
