### ISSUE TITLE
vFlow failing to publish topic in Kafka: name unresolved

### ISSUE THREAD

**Issue by afressancourt** [VerizonDigital/vflow#58]
Hello,

Using the containers indicated in the documentation to test vFlow, my colleague and I have encountered the following error:

`[vflow] 2018/05/25 13:15:42 kafka: Failed to produce message to topic vflow.sflow: dial tcp: lookup <containerID> on <IPGateway>:53: no such host`

This is occurring even if the IP address of the target Kafka is given in the flow.conf file and in the VFLOW_KAFKA_BROKERS environment variable.

This can be solved by adding the target container in the `etc/hosts` file, but this can be an issue on cases that go beyond testing.

**Comment by mehrdadrad** [comment]
@afressancourt pls send me the configuration
