### ISSUE TITLE
Hard coded topic prefix

### ISSUE THREAD

**Issue by DamianZaremba** [VerizonDigital/vflow#6]
The existing producer codes, forces topic names via ([https://github.com/VerizonDigital/vflow/blob/master/producer/producer.go#L75](https://github.com/VerizonDigital/vflow/blob/master/producer/producer.go#L75), [https://github.com/VerizonDigital/vflow/blob/master/vflow/sflow.go#L120](https://github.com/VerizonDigital/vflow/blob/master/vflow/sflow.go#L120) & [https://github.com/VerizonDigital/vflow/blob/master/vflow/ipfix.go#L131](https://github.com/VerizonDigital/vflow/blob/master/vflow/ipfix.go#L131).

This is not preferred for us due to the below reasons:
* Due to the way kafka normalises topics, both '.' and underscore can be interpreted the same way ([https://issues.apache.org/jira/browse/KAFKA-2337](https://issues.apache.org/jira/browse/KAFKA-2337)). To avoid any issues with this, we have an internal standard of not using '.' or '_' in topic names... which unfortunately this breaks.
* We also have an internal naming standard to associate topics to teams/owners.
* It is not possible to run desecrate instances of vflow on the same kafka cluster (for testing/dev environments etc)

Do you have any objects to abstracting this into the config, so the topic names can be specified at runtime.

I can't see a valid reason for this being hard coded, the default could just be set to the existing names to maintain compatibility.

**Comment by mehrdadrad** [comment]
@DamianZaremba right, we need to have the topic names optional.

**Comment by mehrdadrad** [comment]
the changes committed in repo.
