### ISSUE TITLE
Ipfix data samples with custom PENS

### ISSUE THREAD

**Issue by r4ravi2008** [VerizonDigital/vflow#60]
How will the data look like when decoding Information element(IE)s that belong to a custom PEN?

A simple tuple of I, V wouldn't suffice as its quite likely that an IE can belong to a custom PEN with same IE id.

For example when decoding custom IEs tuple can be I, V, E where I is IE id, V is the value and E is the enterprise number, I belongs to.

Reference: https://tools.ietf.org/html/rfc7011#section-3.2

**Comment by mehrdadrad** [comment]
I just added the PEN and it will appear as "E": x if it's not zero/IANA 
I'll try to test it soon but let me know if you get a chance to try it.
