### ISSUE TITLE
netflow  v9: can not read the data

### ISSUE THREAD

**Issue by azsultan2010** [VerizonDigital/vflow#61]
Hi mehrdadrad!

Cisco Catalyst 6509-E streams netflow v9 to vflow.
On some flows it writes to log: cannot read the data. After some time (may pass 1 hr or 1 day) vflow crahes.
Config , log and pcap dump attached.

Thanks!

WBR
Sultan
[vflow.zip](https://github.com/VerizonDigital/vflow/files/2148640/vflow.zip)

**Comment by mehrdadrad** [comment]
Hi @azsultan2010 pls let me know vFlow version and OS? can you attach vflow config?

**Comment by azsultan2010** [comment]
Hi Mehrdadrad,

I beg Your pardon for delay.

Debain stretch (9.4) x86-64

vflow from deb package:
https://github.com/VerizonDigital/vflow/releases/download/v0.4.1/vflow-0.4.1-amd64.deb

confs:
/etc/vflow/vflow.conf
dynamic-workers: false
netflow9-workers: 50
verbose: true
log-file: /var/log/vflow.log
ipfix-enables: false
sflow-enables: false
netflow9-enabled: true
netflow9-port: 4729
netflow-tpl-cache-file: /srv/vflow/netflowv9.templates
mq-name: kafka

/etc/vflow/mq.conf
brokers:
    - 10.1.11.78:9092
    - 10.1.11.79:9092
    - 10.1.11.80:9092
compression: snappy
retry-max: 1
retry-backoff: 10

WBR
Sultan

**Comment by mehrdadrad** [comment]
@azsultan2010 the issue fixed at v0.5.0
