### ISSUE TITLE
Monitoring with influxdb

### ISSUE THREAD

**Issue by parmenides** [VerizonDigital/vflow#63]
How can i use Grafana and InfluxDb for monitoring vflow? I could not find any documentation for enabling monitoring. 
I am running vflow and influxdb on a separate dockers.

**Comment by mehrdadrad** [comment]
@parmenides pls check this:
https://github.com/VerizonDigital/vflow/tree/master/monitor
vFlow exposes metrics through API and there is a sample monitoring collector under /monitor.

**Comment by taq** [comment]
@mehrdadrad , what is that `monitor` command on crontab? I searched for an executable called `monitor` but couldn't find it after installing vflow on Ubuntu.

**Comment by mehrdadrad** [comment]
@taq it collects the vFlow internal metrics (for examples ipfix/sflow/netflow udp packet per seconds or memory heap allocation) and it ingests them to influxdb or tsdb
https://github.com/VerizonDigital/vflow/tree/master/monitor

**Comment by taq** [comment]
Thanks! :-)

**Comment by chrispassas** [comment]
Is there an a grafana dashboard we can download as a starting point?
