### ISSUE TITLE
Error: invalid netflow version (10)

### ISSUE THREAD

**Issue by gedOHub** [VerizonDigital/vflow#65]
When trying to run stress test for vflow getting errors like:

```
invalid netflow version (10)
```

No traffic was parsed and send to kafka cluster.
vflow and strees builded from `v0.5.0` version.

OS: ubuntu 18.04
Java: openjdk version "10.0.1" 2018-04-17
go version: go version go1.10.3 linux/amd64

**Comment by mehrdadrad** [comment]
@gedOHub The stress test doesn't support netflow; it looks you send ipfix stress data to netflow port per error message.
