### ISSUE TITLE
IPFIX/Netflow Definitions

### ISSUE THREAD

**Issue by gsakel1** [VerizonDigital/vflow#68]
Is there a way to add IPFIX and Netflow definitions like so: https://github.com/robcowart/elastiflow/tree/master/logstash/elastiflow/definitions

to the JSON decoder instead of the IANA IPFIX element ID's?

**Comment by mehrdadrad** [comment]
The IPFIX added and I'll try to add same for Netflow, thanks for your suggestion!

**Comment by gsakel1** [comment]
Thank you! Will you update the rpm package to include these changes?

**Comment by mehrdadrad** [comment]
I'll create the new RPM for next release, you can create the RPM easy if you already have GO

**Comment by gsakel1** [comment]
For this to work, all you have to do is add the ipfix.elements file to the /etc/vflow/ directory?

**Comment by mehrdadrad** [comment]
correct and compile w/ the latest version
