### ISSUE TITLE
Multiple message broker destinations

### ISSUE THREAD

**Issue by DamianZaremba** [VerizonDigital/vflow#7]
Currently there is a single publisher that can be specified.

In certain setups, it would be nice to have multiple publishers, including those of the same type.

An example of this would be where there are distinct kafka clusters for redundancy purposes (dual write, dual read), or purpose specific clusters (general vs security for example).

Would it be possible to have multiple instances of publishers, with distinct configs under a single instance? I'm not sure how complex this would be in the current code structure.

An alternate solution is running multiple instances with a proxy in-front (nfacctd etc) or forwarding enabled. Both of these have issues due to #5 and potentially run into local buffer issues.

**Comment by mehrdadrad** [comment]
nice feature, let's keep this open for more discussion and see other idea.
