### ISSUE TITLE
Broker not available

### ISSUE THREAD

**Issue by zaxeqaz** [VerizonDigital/vflow#73]
Hello,

I'm trying to get a new vflow server setup (cisco 4500 > ipfix > vflow > kafka > clickhouse). I think I'm having trouble reaching the kafka broker, but am not sure. Any help would be much apprecited.

error
![image](https://user-images.githubusercontent.com/43657922/46981933-2daccc00-d08f-11e8-9146-b17a3c5e491f.png)

vflow.config
![image](https://user-images.githubusercontent.com/43657922/46981958-47e6aa00-d08f-11e8-964c-6bb831c5f641.png)

mq.config
![image](https://user-images.githubusercontent.com/43657922/46982023-909e6300-d08f-11e8-92da-8569b382f474.png)

Thank you.

**Comment by leoluk** [comment]
This looks like an issue with your Kafka setup, not vflow. Try to send messages to the topic using kafka-console-producer.sh and see if that works.
