### ISSUE TITLE
Kafka consumer for Netflow v9

### ISSUE THREAD

**Issue by eksantrik** [VerizonDigital/vflow#76]
Does anyone know any open-source Kafka consumer to consume netflow v9 topic from vflow and write it into postgresql? 

Thanks,

**Comment by mehrdadrad** [comment]
check the below ipfix consumer  
https://github.com/VerizonDigital/vflow/blob/master/consumers/cli/main.go
and go pq driver github.com/lib/pq
https://astaxie.gitbooks.io/build-web-application-with-golang/en/05.4.html
