### ISSUE TITLE
Hardware specifications and capacity requirements

### ISSUE THREAD

**Issue by eksantrik** [VerizonDigital/vflow#79]
We tried a few commercial solutions but due to their limitations, we decided to build our own Netflow solution with vFlow. We will be using vFlow as part of an architecture for an enterprise environment. Question is that if there has been any study on vFlow's capacity for different hardware specifications. What kind of flow/second can we expect from vFlow? 

Does anyone have any numbers on this?

Thanks

**Comment by leoluk** [comment]
You

**Comment by eksantrik** [comment]
The goal is to process 50K/sec on a single instance. What kind of hardware specs do you think we would need to process such data?

**Comment by mehrdadrad** [comment]
@eksantrik 
One of my collector specification is PowerEdge R620 Intel Xeon E5-2620 2.00GHz, 15 M Cache, 7.2GT/s QPI, Turbo, 6 C, 95W, Max Mem 1333MHz, 64G RAM, Ubuntu. it has 22K sflow UDP packet per seconds load (multi samples) + 3K IPFIX. it means between 25K samples to 125K samples per seconds.
The sar shows 55% CPU idle + 1.5G RAM used
