### ISSUE TITLE
godoc is treating license header as docs

### ISSUE THREAD

**Issue by mmlb** [VerizonDigital/vflow#8]
The current situation is:

```go
// Apache license blurb
// ...
//
package store
...
```
but all the go tools are setup to parse comment immediately before package statement as the package docs. This situation is not very useful. I've verified the following does the right thing.
```go
// Apache license blurb
// ...
//

// Package store stores stuff
// more docs
package store
```

I can submit a PR this is wanted.

**Comment by mmlb** [comment]
and the duplicate package comments should be dropped too.

**Comment by mehrdadrad** [comment]
@mmlb thank you for your suggestion, I tried /store and it works. I need to change all later soon. that's much helpful for other developers if they want to contribute.
