### ISSUE TITLE
Error in parse strings with variable length

### ISSUE THREAD

**Issue by mohamadrezarostami** [VerizonDigital/vflow#80]
According to RFC7011 Section 6.1.6, "The string is sent as an array of zero or more octets using Information Element fixed or variable length." we can have a variable length "In the Template Set, the Information Element Field Length is as 65535.  This reserved length value notifies the that the value of the Information Element will be carried the Information Element content itself." but this is not supported by vFlow and use 65535 for the size of all of the strings.

**Comment by pforemski** [comment]
Agreed, found this after 1h of debugging. Had to trace the ambiguous 'ipfix.go:232: "can not read the data"' error message to actually arrive at ipfix/decoder.go Decoder.decodeData()'s first loop - which is the source of this error message.

This is so disappointing that vFlow actually does not implement IPFIX - but rather a subset of the RFC.

**Comment by mehrdadrad** [comment]
@mohamadrezarostami thanks for catching this! pls resolve the conflict 
BTW our routers send fix len for string/octets

**Comment by mehrdadrad** [comment]
@mohamadrezarostami I merged a [bug fix](https://github.com/VerizonDigital/vflow/commit/819155ee6a9ac9abe25a54bc6aa7a245fe1b0270) right after you changed the decodeData, pls first update your repo then add getDataLength feature to the decodeData. thanks!

**Comment by mohamadrezarostami** [comment]
@mehrdadrad I fix it.
